### ISSUE TITLE
ClassCastException in SwipeAdapter

### ISSUE THREAD

**Issue by pkleczko** [TR4Android/Swipeable-RecyclerView#21]
Hi,

In SwipeAdapter there is a cast from holder view to SwipeItem. However, in your example there is no SwipeItem layout as a root of item view. Also wrapping my item layout into SwipeItem doesn't help. Is there sth I forget to add?

```
java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to com.tr4android.recyclerviewslideitem.SwipeItem
    at com.tr4android.recyclerviewslideitem.SwipeAdapter.onBindViewHolder(SwipeAdapter.java:45)
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)`
```

```java
@Override
public RecyclerView.ViewHolder onCreateSwipeViewHolder(final ViewGroup parent, final int position) {
    ViewPatientHealthItemBinding binding = ViewPatientHealthItemBinding.inflate(LayoutInflater.from(parent.getContext()), parent, false);
    return new ViewHolder(binding.getRoot());
}

@Override
public void onBindSwipeViewHolder(final RecyclerView.ViewHolder viewHolder, final int position) {
    ((ViewHolder) viewHolder).populateData(items.get(position));
}
```

**Comment by taltstidl** [comment]
Hi @pkleczko. Try changing the last parameter of your `inflate` call to `true`, so it looks like this:
```java
ViewPatientHealthItemBinding.inflate(LayoutInflater.from(parent.getContext()), parent, true);
```
That way your list item layout will be directly added as a subview of the `SwipeItem` that handles the swipe to dismiss feature. Otherwise it's not attached and it will fail to find the corresponding `SwipeItem`. See [here](https://developer.android.com/reference/android/view/LayoutInflater.html#inflate(int,%20android.view.ViewGroup,%20boolean)) for more details.

**Comment by pkleczko** [comment]
Hi @TR4Android,

I've tried this but still have the same error. I cleaned and rebuilt app and crash is exactly the same.

`ViewPatientHealthItemBinding binding = ViewPatientHealthItemBinding.inflate(LayoutInflater.from(parent.getContext()), parent, true);`

**Comment by pkleczko** [comment]
Don't uderstand why, but without data binding it works. Maybe there is sth with root view.

**Comment by taltstidl** [comment]
Then it's probably an issue with the data binding library. Unfortunately I don't currently have the time to commit to fixing this issue, so any investigation on this would be greatly appreciated. Thanks for reporting this @pkleczko.

**Comment by djonik1562** [comment]
Hi.
When I had migrated to view binding, I've got the same error ClassCastException in SwipeAdapter. For fix this error I've modified SwipeAdapter:


```java
public final RecyclerView.ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {      
      
     final SwipeItem swipeItem = (SwipeItem) LayoutInflater.from(parent.getContext())
                .inflate(R.layout.item_swipe, parent, false);
        
     final RecyclerView.ViewHolder contentHolder = onCreateSwipeViewHolder(parent, viewType);
       ViewGroup container = swipeItem.findViewById(R.id.swipe_container);
        
      container.addView(contentHolder.itemView);

      swipeItem.setTag(contentHolder);

      return new RecyclerView.ViewHolder(swipeItem) {};
}
```

And added child frameLayout to swipe_item:

```xml
<sedi.android.ui.adapters.recyclerview_slide_adapter.SwipeItem
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">
    
<include
        layout="@layout/item_swipe_info"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />
    
<include
        layout="@layout/item_swipe_undo"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />
    
<FrameLayout
        android:id="@+id/swipe_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
</sedi.android.ui.adapters.recyclerview_slide_adapter.SwipeItem>
```

And:

```java
public RecyclerView.ViewHolder onCreateSwipeViewHolder(ViewGroup parent, int viewType) {
        ItemBourseBinding binding = ItemBourseBinding.inflate(
                LayoutInflater.from(parent.getContext()), parent, false);
        return new Holder(binding);
}
```

And then all worked, but in swipe listener I always get from swipeHolder.getAdapterPosition() value -1 (NO_POSITION).
Can you help me find out why and fix this?

I've figured out. To get position need to use holder.getAdapterPosition, not swipeHolder.getAdapterPosition.
